DEFINITIONS_REGISTRY = {
    "twr": {
        "title": "Time-Weighted Return (TWR)",
        "definition_md": "Daily return: r_t = (V_t - CF_t) / V_{t-1} - 1; TWR = prod(1 + r_t) - 1.",
        "assumptions": "Uses adjusted close prices; cashflows are DEPOSIT/WITHDRAWAL only.",
        "warnings": "Undefined when prior value is missing; UI shows --.",
    },
    "mwr": {
        "title": "Money-Weighted Return (MWR)",
        "definition_md": "IRR on dated cashflows with terminal portfolio value as final inflow.",
        "assumptions": "Includes DEPOSIT/WITHDRAWAL/DIVIDEND/FEE/INTEREST cashflows.",
        "warnings": "Returns None when solver fails to converge.",
    },
    "benchmark_alignment": {
        "title": "Benchmark Alignment",
        "definition_md": "Benchmark is scaled to match portfolio value at first benchmark date.",
        "assumptions": "No explicit calendar alignment between portfolio and benchmark series.",
        "warnings": "Gaps in benchmark series are not filled in UI charts.",
    },
    "max_drawdown": {
        "title": "Max Drawdown",
        "definition_md": "Minimum of drawdown_t = V_t / peak_t - 1 over the series.",
        "assumptions": "Computed on portfolio equity curve.",
        "warnings": "Unavailable when equity curve is empty.",
    },
    "current_drawdown": {
        "title": "Current Drawdown",
        "definition_md": "Latest drawdown_t = V_t / peak_t - 1.",
        "assumptions": "Computed on portfolio equity curve.",
        "warnings": "Unavailable when equity curve is empty.",
    },
    "rolling_volatility": {
        "title": "Rolling Volatility",
        "definition_md": "Rolling standard deviation of daily portfolio returns.",
        "assumptions": "No annualization applied in the UI chart.",
        "warnings": "NaN when returns are missing.",
    },
    "sharpe_rolling": {
        "title": "Rolling Sharpe",
        "definition_md": "Rolling mean/volatility * sqrt(252).",
        "assumptions": "Uses daily portfolio returns.",
        "warnings": "NaN when volatility is zero or missing.",
    },
    "var_daily": {
        "title": "Value at Risk (Daily)",
        "definition_md": "VaR = quantile(returns, 1 - confidence).",
        "assumptions": "Uses empirical distribution of daily returns.",
        "warnings": "NaN when returns are missing.",
    },
    "cvar_daily": {
        "title": "Conditional VaR (Daily)",
        "definition_md": "CVaR = mean(returns <= VaR).",
        "assumptions": "Uses empirical distribution of daily returns.",
        "warnings": "NaN when returns are missing.",
    },
    "factor_tilts": {
        "title": "Factor Tilts",
        "definition_md": "Tilt = mean(portfolio factor pct) - mean(universe factor pct).",
        "assumptions": "Portfolio = watchlist tickers; universe = scores_daily.",
        "warnings": "Empty when scores or tickers are missing.",
    },
    "component_risk": {
        "title": "Component Risk Contribution",
        "definition_md": "Contribution = (w * (cov @ w)) / (w.T @ cov @ w).",
        "assumptions": "Uses covariance of daily returns.",
        "warnings": "Empty when weights sum to zero or variance is zero.",
    },
    "allocation_effect": {
        "title": "Allocation Effect",
        "definition_md": "Portion of return explained by portfolio weights versus equal-weight benchmark.",
        "assumptions": "Uses equal-weight benchmark and daily returns.",
        "warnings": "Can be near total return for single-asset portfolios.",
    },
    "selection_effect": {
        "title": "Selection Effect",
        "definition_md": "Portion of return explained by asset performance vs benchmark return.",
        "assumptions": "Uses equal-weight benchmark return per period.",
        "warnings": "Zero when asset returns match benchmark return.",
    },
    "interaction_effect": {
        "title": "Interaction Effect",
        "definition_md": "Residual effect of weights and relative asset performance.",
        "assumptions": "Equal-weight benchmark weights.",
        "warnings": "Can be small in short windows.",
    },
    "tracking_error": {
        "title": "Tracking Error",
        "definition_md": "Std dev of active returns (portfolio - benchmark), annualized by sqrt(252).",
        "assumptions": "Aligned portfolio and benchmark return series.",
        "warnings": "Unavailable when active returns are insufficient.",
    },
    "benchmark_volatility": {
        "title": "Benchmark Volatility",
        "definition_md": "Annualized std dev of benchmark daily returns.",
        "assumptions": "Uses daily benchmark returns.",
        "warnings": "Unavailable with insufficient data.",
    },
    "benchmark_correlation": {
        "title": "Benchmark Correlation",
        "definition_md": "Correlation of portfolio and benchmark daily returns.",
        "assumptions": "Uses overlapping daily returns.",
        "warnings": "Unavailable with insufficient data.",
    },
    "correlation_matrix": {
        "title": "Correlation Matrix",
        "definition_md": "Pairwise correlation of asset daily returns over the analysis window.",
        "assumptions": "Requires minimum history and aligned return observations.",
        "warnings": "Partial matrices exclude assets with insufficient data.",
    },
    "rolling_drawdown": {
        "title": "Rolling Drawdown",
        "definition_md": "Rolling minimum of drawdown over the window.",
        "assumptions": "Uses portfolio drawdown series.",
        "warnings": "Empty when window insufficient.",
    },
    "attribution_30d": {
        "title": "Attribution (30d)",
        "definition_md": "Contribution proxy = mean(returns_30d) * weight.",
        "assumptions": "Weights from watchlist.yml or equal weight.",
        "warnings": "Empty when returns unavailable.",
    },
    "price_spot": {
        "title": "Price",
        "definition_md": "Latest adjusted close stored in scores_daily.Price.",
        "assumptions": "Computed in pipeline from prices_daily.",
        "warnings": "Missing when price history insufficient.",
    },
    "composite_pct": {
        "title": "Composite Percentile",
        "definition_md": "Percentile rank of Composite score in the universe.",
        "assumptions": "Computed in pipeline as rank(pct=True) * 100.",
        "warnings": "Missing when scores are empty.",
    },
    "value_pct": {
        "title": "Value Percentile",
        "definition_md": "Percentile rank of ValueScore in the universe.",
        "assumptions": "Computed in pipeline as rank(pct=True) * 100.",
        "warnings": "Missing when scores are empty.",
    },
    "quality_pct": {
        "title": "Quality Percentile",
        "definition_md": "Percentile rank of QualityScore in the universe.",
        "assumptions": "Computed in pipeline as rank(pct=True) * 100.",
        "warnings": "Missing when scores are empty.",
    },
    "momentum_pct": {
        "title": "Momentum Percentile",
        "definition_md": "Percentile rank of MomScore in the universe.",
        "assumptions": "Computed in pipeline as rank(pct=True) * 100.",
        "warnings": "Missing when scores are empty.",
    },
    "piotroski_f": {
        "title": "Piotroski F-score",
        "definition_md": "Nine-signal fundamental quality score (0-9).",
        "assumptions": "Computed in pipeline from fundamentals rollups.",
        "warnings": "Missing when fundamentals are absent.",
    },
    "volatility_30d": {
        "title": "Volatility 30d",
        "definition_md": "Std of last ~30 daily returns, annualized by sqrt(252).",
        "assumptions": "Computed in pipeline on adjusted close returns.",
        "warnings": "Missing when price history is insufficient.",
    },
    "sharpe_1y": {
        "title": "Sharpe 1y",
        "definition_md": "Mean/vol of last ~252 daily returns, annualized by sqrt(252).",
        "assumptions": "Computed in pipeline on adjusted close returns.",
        "warnings": "Missing when price history is insufficient.",
    },
    "drawdown_1y": {
        "title": "Drawdown 1y",
        "definition_md": "Last price vs max over trailing ~252 sessions: last / peak - 1.",
        "assumptions": "Computed in pipeline on adjusted close prices.",
        "warnings": "Missing when price history is insufficient.",
    },
    "sma_20": {
        "title": "SMA 20",
        "definition_md": "20-day rolling mean of adjusted close.",
        "assumptions": "Computed locally in Stock Research.",
        "warnings": "Missing when price history is insufficient.",
    },
    "sma_50": {
        "title": "SMA 50",
        "definition_md": "50-day rolling mean of adjusted close.",
        "assumptions": "Computed locally in Stock Research.",
        "warnings": "Missing when price history is insufficient.",
    },
    "rsi_14": {
        "title": "RSI 14",
        "definition_md": "14-day Relative Strength Index computed from adjusted close.",
        "assumptions": "Computed locally in Stock Research.",
        "warnings": "Missing when price history is insufficient.",
    },
    "latest_daily_return": {
        "title": "Latest Daily Return",
        "definition_md": "Most recent portfolio daily return.",
        "assumptions": "Uses portfolio daily returns series.",
        "warnings": "Unavailable when returns are empty.",
    },
    "return_7d": {
        "title": "7-day Return",
        "definition_md": "Compounded return over last 7 daily returns.",
        "assumptions": "Uses portfolio daily returns series.",
        "warnings": "Unavailable when less than 7 data points.",
    },
}
